server:
  ldap:
    enabled: false
    host: example.com
    base: dc=example,dc=com
    port: 389
    use_ssl: false
    bind_dn: uid=bind,ou=dev,dc=example,dc=com
    bind_password: 123456
    user_filter:  (uid=%s)
    group_filter:
    attributes:
    - givenName
    - sn
    - mail
    - uid
  addr: :11313
db:
  db_type: mysql
  db_dsn: gosuv_db:123456@tcp(127.0.0.1:3306)/gosuv_db?tls=skip-verify&autocommit=true
host: .
admins:
- user1
- user2
